# -*- coding: utf-8 -*-
# """AQI_2.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1a_uSwXoGVUesl1ulzUZCiJwR4IaU7HlI

# #Air Quality Index Analysis and Prediction

# ###Pmdarima Library

#  This library provides automated grid search (auto_arima) to find the optimal
#  p, d, q parameters for our ARIMA time-series models a cities.
#  <br>
#  pip install streamlit pandas numpy matplotlib seaborn scikit-learn statsmodels pmdarima prophet plotly cmdstanpy
# """

# !pip install pmdarima streamlit

# """import required modeules from respective libraries"""

import streamlit as st
import pmdarima as pm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.arima.model import ARIMA
import pmdarima as pm
from prophet import Prophet
from prophet.plot import add_changepoints_to_plot
from sklearn.metrics import mean_absolute_error
import logging
st.set_page_config(layout='wide')
logging.getLogger('prophet').setLevel(logging.ERROR)
st.write("Project title: Air Quality Index Analysis and Prediction")
st.write('Name:Komal Dheer')
st.write('Registered email id: lxmn.dheer@gmail.com')
st.title('AQI Forecasting App')
st.title('Models used: ARIMA and Prophet')
st.write('This app forecasts AQI for selected cities in India using ARIMA and Prophet models. The models  are trained on  data from 2015-01-01 to 2019-12-31.')
forecast_tab, policy_tab = st.tabs(["Forecast", "Actionable Policy Insights"])
with forecast_tab:
    @st.cache_resource
    def load_data():
      data_url = "https://raw.githubusercontent.com/adityarc19/aqi-india/refs/heads/main/city_day.csv"
      try:
        df = pd.read_csv(data_url)
        print("Dataset fetched successfully!")
        print(f"Dataset Shape: {df.shape[0]} rows and {df.shape[1]} columns.\n")

      except Exception as e:
        print(f"Network configuration error: {e}")
      df['Date']=pd.to_datetime(df['Date'])
      aqi_map={'Good':0,'Satisfactory':1,'Moderate':2,'Poor':3,'Very Poor':4,'Severe':5}
      df['AQI_Bucket']=df['AQI_Bucket'].map(aqi_map);

      return df
df=load_data()

print('='*10,"Dataframe Information ",'='*60)
print(df.info())
print("Cities:",df['City'].unique())

# """####Correlation
# Analyzing correlation among different features of the dataset
# """

num_cols=[x for x in df.columns if df[x].dtype==np.float64]
num_df=df[num_cols]
matrix=num_df.corr()
sns.heatmap(matrix,cmap='viridis',linewidth=0.5)
plt.savefig('correlation.png', dpi=300)

# """Based on correlation matrix observation we can conclude that feature which have moderate correlation with AQI are- CO,PM10,PM2.5,SO2,NO2,NO and NOx

# ####selecting cities for prediction based on
# 1.number of rows
# <br>2.percentage of missing AQI entries
# """

@st.cache_resource
def get_cities():
  un_city=df['City'].unique()
  print('percentage of missing entries:')
  for city in un_city:
    cdf=df[df['City']==city]
    total=len(cdf)
    aqi_missing_percentage = cdf['AQI'].isnull().sum()/total*100
    print(f'{city.upper():<12} \ttotal:{total}\tMissing:{aqi_missing_percentage:.2f}%')

  cities=[city for city in un_city if len(df[df['City']==city])>1600]
  cities.remove('Mumbai')
  cities.remove('Ahmedabad')
  return cities
cities=get_cities()
print('\nSelected Cities',cities)

# """Among all cities having total number of rows greater than 1600 we dropped Mumbai and Ahmedabad from cities list as the percentages of missing AQI entries int these subsets of dataframe are 61.42 and 33.60% respectively

# ###Time series Interpolation
# to fill missing values in arima and prophet we should use time series interpolation
# <br><br>
# Linear Interpolation estimates missing values by drawing a straight line between the two closest known data points in time
# """

@st.cache_resource
def get_separate_df():
  df_list={}
  for city in cities:
    curr_df=df[df['City']==city].copy()
    curr_df.set_index('Date',inplace=True)
    full_range=pd.date_range(start=curr_df.index.min(),end=curr_df.index.max(),freq='D')
    curr_df = curr_df.reindex(full_range)

    numerical_cols = [col for col in curr_df.columns if curr_df[col].dtype == np.float64 and col != 'AQI_Bucket']
    for col in numerical_cols:
      curr_df[col] = curr_df[col].interpolate(method='linear')
      curr_df[col] = curr_df[col].clip(lower=0)

    curr_df['AQI_Bucket'] = curr_df['AQI_Bucket'].ffill().bfill()

    curr_df=curr_df.ffill().bfill()

  # Adding dataframe to the list of dataframe for different cities
    curr_df=curr_df.drop('City',axis=1)
    df_list[city]=curr_df
  return df_list
df_list=get_separate_df()
with forecast_tab:
  days=st.slider("days to forecast(after 1-Jan-2020):",1,365,30)
  chosen_city=st.selectbox('Select city:',cities)
  col1,col2,col3=st.columns(3)

# """####ploting AQI for the selected cities over given time period"""

draw_df=df_list[chosen_city].copy()
draw_df['Mean_AQI_20'] = draw_df['AQI'].rolling(window=20).mean()
draw_df['Mean_AQI_60'] = draw_df['AQI'].rolling(window=60).mean()

# 2. Setup the plot
fig, ax = plt.subplots(figsize=(12, 5))

# 3. Plot using df.index explicitly and your desired colors
ax.plot(draw_df.index, draw_df['AQI'], color='skyblue', label='Daily AQI', alpha=0.8)
ax.plot(draw_df.index, draw_df['Mean_AQI_20'], color='gray', label='20-day Mean AQI', linewidth=2)
ax.plot(draw_df.index, draw_df['Mean_AQI_60'], color='blue', label='60-day Mean AQI', linewidth=2)

# 4. Formatting
ax.set_title('AQI Levels and Moving Averages')
ax.set_xlabel('Date')
ax.set_ylabel('AQI')
ax.grid(True, linestyle='--', alpha=0.6)
ax.legend()

plt.tight_layout()
with forecast_tab:
  col3.pyplot(fig)
plt.close(fig)
draw_df=draw_df.drop(columns=['Mean_AQI_20','Mean_AQI_60'])

# """### Feature Engineering for Time Series Models

# Now that the data is cleaned and interpolated, we'll create additional features that can help ARIMA and Prophet models capture patterns more effectively. These include:

# 1.  **Time-based Features**: Extracting components like year, month, day of week, etc., from the date index.

# """

# 1. Create Time-based Features
@st.cache_resource
def add_time_features():
  for city, curr_df in df_list.items():
    curr_df['Year'] = curr_df.index.year
    curr_df['Month'] = curr_df.index.month
    curr_df['Day'] = curr_df.index.day
    curr_df['DayOfWeek'] = curr_df.index.dayofweek # Monday=0, Sunday=6
    curr_df['DayOfYear'] = curr_df.index.dayofyear
    curr_df['WeekOfYear'] = curr_df.index.isocalendar().week.astype(int)
    curr_df['Quarter'] = curr_df.index.quarter
    df_list[city] = curr_df.copy() # Update the df_list with new features
    #removing empty columns
  for city in df_list:
    for col in df_list[city]:
      if df_list[city][col].isnull().sum()==len(df_list[city]):
        df_list[city]=df_list[city].drop(columns=[col])

  return df_list
df_list=add_time_features()
print("Time-based features added to each city's DataFrame.")

# rrelation matrix including the time based features"""

fig,ax = plt.subplots(figsize=(10,10))
city_num_df = df_list[chosen_city].select_dtypes(include=np.number)
matrix = city_num_df.corr()
sns.heatmap(matrix, cmap='Blues_r', linewidths=0.5, ax=ax)
ax.set_title(f'Correlation Matrix for {chosen_city}', fontsize=14)

plt.tight_layout()
with forecast_tab:
  col3.pyplot(fig)# Adjust layout to prevent overlapping titles/labels
plt.close(fig)

# """AQI score of Patna ,Delhi and Gurugram show comparatively higher correlaion with pollutant concentrations<br><br>
# Based on correlation matrix of different cities we can decide the exogenous features for our model
# """

@st.cache_resource
def get_exog_features():
  exog_features={}
  for city in cities:
    aqi_corr= df_list[city].corr(numeric_only=True)['AQI']
    aqi_corr_sorted = aqi_corr.sort_values(ascending=False)
    aqi_corr_clean = aqi_corr_sorted.drop('AQI')
    aqi_corr_clean= aqi_corr_clean.drop('AQI_Bucket')
    exog_=aqi_corr_clean[(aqi_corr_clean>=0.4) | (aqi_corr_clean<=-0.3)]
    if 'Year' in exog_:
      exog_=exog_.drop('Year')
    exog_features[city]=exog_.index.tolist()
  return exog_features
exog_features=get_exog_features()
for city in cities:
  print(f'{city:<10}:{exog_features[city]}')

print(df_list['Patna'].info())

# """#Using ARIMA for predictions
# **pmdarima**:(originally called pyramid-arima) is a statistical Python library dedicated entirely to time-series analysis and forecasting.
# <br><br>
# we will use pmdarima's Automated Hyperparameter Tuning feature (auto_arima) to find the optimal ARIMA parameters
# """

@st.cache_resource
def get_arima_models():
  train_df={}
  test_df={}
  arima_models={}
  split_date='2020-01-01'
  for city,data in df_list.items():
    train_df[city]=data.loc[:split_date,:]
    test_df[city]=data.loc[split_date:,:]

    #test stationarity of all datasets in list
    print(city)
    adf_stat=adfuller(data['AQI'])[0]
    p_val=adfuller(data['AQI'])[1]
    print('ADF statistic:',adf_stat,'\tp-value:',p_val)

    #find best model parameters
    auto_model = pm.auto_arima(
      data['AQI'],
      start_p=1, start_q=1,
      max_p=5, max_q=5,
      d=None,           # Let the algorithm determine the best 'd' automatically
      seasonal=False,
      trace=False,
      error_action='ignore',
      suppress_warnings=True,
      stepwise=True
    )
    p,d,q=auto_model.order
    print(f'ARIMA Order:{p,d,q}\n')
    model = ARIMA(train_df[city]['AQI'], order=(p, d, q),exog=train_df[city][exog_features[city]])
    model_fitted = model.fit()
    arima_models[city]=model_fitted
  return train_df,test_df,arima_models
train_df,test_df,arima_models=get_arima_models()

# """making predictions from the created model and measure mean absolute error for each city's prediction results"""

#predicting and testing accuracy of results
split_date='2020-01-01'
arima_mae={}
for city in cities:
  all_exog_features=exog_features[city]
  # forecast should start one day after split date
  forecast_start_date = pd.to_datetime(split_date) + pd.Timedelta(days=1)
  forecast_end_date = test_df[city].index.max()
  exog_data_for_prediction = test_df[city].loc[forecast_start_date:forecast_end_date, all_exog_features]
  predictions=arima_models[city].predict(start=forecast_start_date, end=forecast_end_date, exog=exog_data_for_prediction)
  actual_aqi = test_df[city]['AQI'].loc[forecast_start_date:forecast_end_date]
  mae=mean_absolute_error(actual_aqi,predictions)
  print(f'Mean Absolute Error for {city :<12}:{mae:.4f}\n')
  arima_mae[city]=mae

# """#Using Prophet for prediction
# Prophet approaches time-series forecasting as a curve-fitting exercise rather than looking at sequential dependencies (like ARIMA or LSTM models). It frames the problem as an additive regression model composed of four distinct components**trend,seasonability,holidays,error**
# """

changepoint_prior_scale_list={"Bengaluru":0.008,"Chennai":0.10,"Delhi":0.10,"Hyderabad":0.01,"Lucknow":0.82,"Gurugram":0.05,"Patna":0.05}
seasonality_mode_list={"Bengaluru":'additive',"Chennai":'multiplicative',"Delhi":'additive',"Hyderabad":'additive',"Lucknow":'multiplicative',"Gurugram":'multiplicative',"Patna":"multiplicative"}
seasonality_prior_scale_list={"Bengaluru":5,"Chennai":2,"Delhi":10,"Hyderabad":10,"Lucknow":10,"Gurugram":10,"Patna":11}
holidays_prior_scale_list={"Bengaluru":2,"Chennai":20,"Delhi":10,"Hyderabad":10,"Lucknow":10,"Gurugram":10,"Patna":10}

@st.cache_resource
def get_prophet_models():
  simple_prophet_models={}
  prophet_models={}
  prophet_mae={}
  for city in df_list:
    prophet_df=df_list[city].reset_index().rename(columns={'index':'ds','AQI':'y'})

    m=Prophet(
        changepoint_prior_scale=changepoint_prior_scale_list[city],
        seasonality_mode=seasonality_mode_list[city],
        seasonality_prior_scale=seasonality_prior_scale_list[city],
        holidays_prior_scale=holidays_prior_scale_list[city]
        )
    # Initialize simple_m as a separate Prophet instance without regressors
    simple_m=Prophet(
        changepoint_prior_scale=changepoint_prior_scale_list[city],
        seasonality_mode=seasonality_mode_list[city],
        seasonality_prior_scale=seasonality_prior_scale_list[city],
        holidays_prior_scale=holidays_prior_scale_list[city]
        )

    regressor_cols = exog_features[city]
    for col in regressor_cols:
      if col in prophet_df.columns:
        m.add_regressor(col)
    simple_train= prophet_df[prophet_df['ds'] <= pd.to_datetime(split_date)][['ds', 'y']]
    train_prophet_df = prophet_df[prophet_df['ds'] <= pd.to_datetime(split_date)][['ds', 'y'] + regressor_cols]
    simple_m.fit(simple_train)
    m.fit(train_prophet_df)
    prophet_models[city]=m
    simple_prophet_models[city]=simple_m

    future = prophet_df[prophet_df['ds'] > pd.to_datetime(split_date)][['ds'] + regressor_cols]
    predictions=m.predict(future)

    print(city)
    actual_y_test = prophet_df[prophet_df['ds'] > pd.to_datetime(split_date)]['y']
    mae=mean_absolute_error(actual_y_test,predictions['yhat'])
    print(f'Mean Absolute Error:{mae:.4f}')
    prophet_mae[city]=mae
  return prophet_models,prophet_mae,simple_prophet_models
prophet_models,prophet_mae,simple_prophet_models=get_prophet_models()

# """comparing performance of ARIMA and Prophet"""

for city in cities:
  print(city)
  ar_mae=arima_mae[city]
  pt_mae=prophet_mae[city]
  print(f'ARIMA:{ar_mae:.2f}\tProphet:{pt_mae:.2f}\n')

# """For all cities except Chennai prophet gives better results

# """

arima_table = pd.DataFrame(columns=['Date', 'ARIMA AQI'])
prophet_table = pd.DataFrame(columns=['Date', 'Prophet AQI'])

if col2.button("Forecast"):
    st.subheader(f"Forecast comparison for {chosen_city}")
    st.write(f"ARIMA MAE: {arima_mae[chosen_city]:.2f} | Prophet MAE: {prophet_mae[chosen_city]:.2f}")

    prophet_future = simple_prophet_models[chosen_city].make_future_dataframe(periods=days)
    prophet_forecast = simple_prophet_models[chosen_city].predict(prophet_future)
    prophet_table = prophet_forecast[['ds', 'yhat']].tail(days).copy()
    prophet_table = prophet_table.rename(columns={'ds': 'Date', 'yhat': 'Prophet AQI'})

    arima_start = pd.to_datetime('2020-01-01') + pd.Timedelta(days=1)
    arima_end = min(arima_start + pd.Timedelta(days=days - 1), test_df[chosen_city].index.max())
    arima_exog = test_df[chosen_city].loc[arima_start:arima_end, exog_features[chosen_city]]
    arima_predictions = arima_models[chosen_city].predict(
        start=arima_start,
        end=arima_end,
        exog=arima_exog
    )
    arima_table = pd.DataFrame({
        'Date': arima_predictions.index,
        'ARIMA AQI': arima_predictions.values
    })

    

    with forecast_tab:
        col1.subheader("ARIMA Forecast")
        col1.dataframe(arima_table, use_container_width=True)

        col2.subheader("Prophet Forecast")
        col2.dataframe(prophet_table, use_container_width=True)

with policy_tab:
  policy_tab.subheader(f"Policy actions for {chosen_city}")

  if arima_table.empty or prophet_table.empty:
      policy_tab.info("Click 'Forecast' to generate forecast tables and view policy recommendations.")
  else:
      avg_aqi = round((arima_table['ARIMA AQI'].mean() + prophet_table['Prophet AQI'].mean()) / 2, 2)
      policy_tab.metric("Forecasted average AQI", f"{avg_aqi}")

      if avg_aqi <= 50:
          severity = "Good"
          actions = [
              "Maintain current emissions controls and urban mobility measures.",
              "Continue public transport incentives and green-space maintenance.",
              "Keep routine monitoring for seasonal smoke or dust spikes."
          ]
      elif avg_aqi <= 100:
          severity = "Satisfactory"
          actions = [
              "Increase roadside dust control and strict enforcement of construction site watering.",
              "Promote travel demand management during morning and evening peak hours.",
              "Issue public health reminders for sensitive groups when AQI rises further."
          ]
      elif avg_aqi <= 200:
          severity = "Moderate"
          actions = [
              "Activate temporary traffic and industrial emission checks in high-pollution zones.",
              "Prioritize public transport and stagger work hours to reduce congestion.",
              "Alert schools and hospitals to monitor vulnerable populations."
          ]
      elif avg_aqi <= 300:
          severity = "Poor"
          actions = [
              "Introduce short-term odd-even vehicle restrictions or congestion pricing in hotspots.",
              "Mandate stricter controls on open burning, diesel generators, and construction dust.",
              "Issue health advisories for children, seniors, and people with respiratory illness."
          ]
      elif avg_aqi <= 400:
          severity = "Very Poor"
          actions = [
              "Trigger emergency pollution response plans with stronger industrial monitoring.",
              "Restrict high-emission truck movement and suspend non-essential open burning.",
              "Coordinate with health services to increase respiratory support capacity."
          ]
      else:
          severity = "Severe"
          actions = [
              "Activate emergency AQI response procedures and temporary public safety advisories.",
              "Deploy immediate restrictions on heavy industry, waste burning, and diesel traffic in affected sectors.",
              "Escalate public communication and medical preparedness for severe respiratory risk."
          ]

      policy_tab.write(f"Expected AQI band: {severity}")
      policy_tab.write("Recommended policy actions:")
      for action in actions:
          policy_tab.write(f"- {action}")