# # -*- coding: utf-8 -*-
# """Iris_Flower_Classification.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1zpu8LJ4VJgL_WUS2SsiNKIkNimLKgA4F
# """

# !pip install streamlit

#iris flower classification
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
st.set_page_config(page_title="Iris Flower Classification", layout="wide")
st.write("Project Title: Iris Flower Classification")
st.write("Name:Komal Dheer")
st.write("Registered email ID: lxmn.dheer@gmail.com")
st.title("Iris Flower Classification")
st.write("This is a simple Streamlit app for classifying iris flowers based on their features using Logistic Regression.")
tab1, tab2 = st.tabs(["Model Evaluation", "Data Visualization"])
with tab1:
    container1=st.container(border=True)
    with container1:
        c1,c2,c3,c4=container1.columns(4)
        c1.number_input("Enter Sepal Length (cm):", min_value=0.0, max_value=10.0, value=5.1, step=0.1, key="sepal_length")
        c2.number_input("Enter Sepal Width (cm):", min_value=0.0, max_value=10.0, value=3.5, step=0.1, key="sepal_width")
        c3.number_input("Enter Petal Length (cm):", min_value=  0.0, max_value=10.0, value=1.4, step=0.1, key="petal_length")
        c4.number_input("Enter Petal Width (cm):", min_value=0.0, max_value=10.0, value=0.2, step=0.1, key="petal_width")
    container2=st.container(border=True)
with tab2:
    col1,col2,col3=st.columns(3)
#load iris dataset
@st.cache_resource
def get_data():
  iris = load_iris()
  X = pd.DataFrame(iris.data, columns=iris.feature_names)
  y = pd.Series(iris.target, name='species')
  return X,y

X,y=get_data()
print("Features (X):")
print(X.head())
print("\nTarget (y):")
print(y.head())

df = X.copy()
df['species'] = y

# Replace numerical species with actual names for better readability in plots
df['species'] = df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# 1. Initialize the figure
fig, ax = plt.subplots(figsize=(8, 6))

# 2. Corrected to sns.scatterplot to use hue, palette, and data properly
sns.scatterplot(
    x="sepal length (cm)",
    y="sepal width (cm)",
    hue="species",
    data=df,
    palette="viridis",
    s=100,
    alpha=0.8,
    ax=ax,  # Tells Seaborn to draw on your 'ax' object
)

# 3. Fixed method names (added '.set_')
ax.set_title("Sepal Length vs. Sepal Width by Species")
ax.set_xlabel("Sepal Length (cm)")
ax.set_ylabel("Sepal Width (cm)")

# 4. Grid and Legend
ax.grid(True, linestyle="--", alpha=0.7)
ax.legend(title="Species")

# 5. Display on Streamlit
with tab2:
    col1.pyplot(fig)

fig2, ax2 = plt.subplots(figsize=(8, 6))
sns.scatterplot(x='petal length (cm)', y='petal width (cm)', hue='species', data=df, palette='magma', s=100, alpha=0.8)
ax2.set_title('Petal Length vs. Petal Width by Species')
ax2.set_xlabel('Petal Length (cm)')
ax2.set_ylabel('Petal Width (cm)')
ax2.grid(True, linestyle='--', alpha=0.7)
ax2.legend(title='Species')
with tab2:
    col2.pyplot(fig2)

figure, axes = plt.subplots(2, 2, figsize=(8, 4))
axes = axes.flatten()

for i, col in enumerate(X.columns):
    sns.histplot(df[col], kde=True, ax=axes[i], color='skyblue')
    axes[i].set_title(f'Distribution of {col}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frequency')

plt.tight_layout()
with tab2:
    st.pyplot(figure)

X = df.drop('species', axis=1)
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

model = LogisticRegression(max_iter=200, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
input_features = np.array([[st.session_state.sepal_length, st.session_state.sepal_width, st.session_state.petal_length, st.session_state.petal_width]])
predicted_species = model.predict(input_features)[0]
cm1,cm2=container2.columns(2)
if container1.button("Predict Species"):
    cm1.markdown(f"The predicted species for the given features is: **{predicted_species}**")
    cm1.divider()
cm1.write("Classification Report:")
cm1.text(classification_report(y_test, y_pred))

cm_fig, cm_ax = plt.subplots(figsize=(8, 6))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues',
            xticklabels=model.classes_, yticklabels=model.classes_, ax=cm_ax)
cm_ax.set_xlabel('Predicted Label')
cm_ax.set_ylabel('True Label')
cm_ax.set_title('Confusion Matrix for Iris Classification')
cm2.pyplot(cm_fig)

